### ISSUE TITLE
Error in getter for watcher "visibleRows": "TypeError: sortValueA.localeCompare is not a function"

### ISSUE THREAD

**Issue by vayter2** [arnedesmedt/vue-ads-table-tree#11]
Hello, 

thanks for good work.

I'm getting this error when pressing sort arrow at column's header:

`Error in getter for watcher "visibleRows": "TypeError: sortValueA.localeCompare is not a function"`

Could you please help?

Regards, E.

**Comment by arnedesmedt** [comment]
Hello,

Thx for the appreciation.

Would you like to check first if you're on the last version, namely 1.2.5

This is the part of the code where something goes wrong:

```
let sortValueA = rowA.properties[column.property];
let sortValueB = rowB.properties[column.property];
return (column.direction ? 1 : -1) * ('' + sortValueA.localeCompare(sortValueB));
```

I will need to change my code so that if no sortValue is found (because the property is not set on that row) a default value like an empty string is given.

But maybe you can already solve the problem by yourself. You need to check that each row contains the column property you're sorting. If that's the case, the error will be gone.

**Comment by vayter2** [comment]
Thanks for quick response.

My current installed version is 1.2.5.

I have a column with a boolean row values: they are always `true` or `false`, there are no `undefined` or `null` or absent property. And anyway I getting this error while sorting.

**Comment by arnedesmedt** [comment]
That's the reason why it doesn't work, localCompare is a string method and you can't use it for booleans. I will add this on my planning, so you can sort on every type you like.

**Comment by vayter2** [comment]
Ok, thanks. 
Prevoiusly I was sure that I always getting a string to compare at this line using casting `' ' +`: 
`(' ' + sortValueA.localeCompare(sortValueB))`.
Much appreciate your help.
