### ISSUE TITLE
missing sort icons

### ISSUE THREAD

**Issue by ray007** [arnedesmedt/vue-ads-table-tree#17]
Without extra work, the icons for sorting from fontawewsome do not show up.

**Comment by arnedesmedt** [comment]
If you check my demo, you can see that the font awesome icons are listed as a resource.

You will have to import them by yourself. 
See https://jsfiddle.net/arnedesmedt/7my8L42q and open the resources panel on the left.

I can't include all those icons in the library because it will increase the size of the package and their can be cases where you don't use the icons, for example use your own icons, or don't use any icons if you use the table as a basic table.

**Comment by ray007** [comment]
Yes, they're in the demo. Which is where I found out about them.
I just thought it would be nice to mention it in the readme.

**Comment by arnedesmedt** [comment]
I'll reopen this issue to mention it in the readme.

**Comment by arnedesmedt** [comment]
It is mentioned in the readme.
